# Generated by Django 5.1 on 2024-09-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0004_materias_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='materias',
            name='nivel_escolar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.nivelescolar'),
        ),
    ]
