# Generated by Django 5.1 on 2024-09-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0005_nivelescolar_materias_nivel_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='nivel_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.nivelescolar'),
        ),
    ]
