# Generated by Django 5.1 on 2024-09-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0006_alter_materias_nivel_escolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='descripcion',
        ),
    ]
