# Generated by Django 5.1 on 2024-09-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0007_remove_materias_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
