# Generated by Django 5.1 on 2024-09-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0008_materias_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='fecha_limite',
            new_name='fechaLimite',
        ),
    ]
