# Generated by Django 5.1 on 2024-10-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0009_rename_fecha_limite_asignacion_fechalimite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='materia',
            new_name='nombre',
        ),
    ]
