# Generated by Django 5.1 on 2024-10-02 01:17

import usuarios_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0010_rename_materia_asignacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='nombre',
            field=models.TextField(verbose_name=usuarios_api.models.Materias),
        ),
    ]
