# Generated by Django 5.1 on 2024-10-06 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0013_userprofile_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudiante'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profesor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.profesor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(related_name='estudiante_materias', to='usuarios_api.materias'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(related_name='profesor_materias', to='usuarios_api.materias'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
